version: "3"

services:
  mimir:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir
    volumes:
      - ./mimir-1node-config.yaml:/etc/mimir.yaml
      - mimir-data:/data
    ports:
      - 9009:9009

volumes:
  mimir-data:
